### ISSUE TITLE
关于解决“minimatch”体积过大的问题

### ISSUE THREAD

**Issue by lemondreamtobe** [varletjs/axle#13]
作为强迫症患者，很难忍受一个包占据55kb的事实

建议作者使用 matcher

单纯比较字符串来说 轻量很多

希望看到一个比较轻量的版本

**Comment by haoziqaq** [comment]
micromatch 可能也是个选择，抽空尝试替换一下

**Comment by lemondreamtobe** [comment]
> 大体看了一下仓库 readme，似乎只支持通配符 match，而不支持 glob ？

glob?你还要支持node吗？如果只要纯客户端 感觉match 就行了，我目前打算基于他的代码自行改造

或者说建议直接出一个client版本的axle

**Comment by lemondreamtobe** [comment]
> micromatch

micromatch 好在支持es，但是体积没有明显差距

**Comment by haoziqaq** [comment]
> > 大体看了一下仓库 readme，似乎只支持通配符 match，而不支持 glob ？
> 
> glob?你还要支持node吗？如果只要纯客户端 感觉match 就行了，我目前打算基于他的代码自行改造
> 
> 或者说建议直接出一个client版本的axle

当然，axios 同样支持 nodejs，服务端也需要发送请求。

**Comment by haoziqaq** [comment]
micromatch 似乎没有对 browser 做第一方兼容，哈哈。目前没有发现什么特别合适的 minimatch 替代品。

**Comment by haoziqaq** [comment]
如果你有好的替代品也可以尝试 pr。
