### ISSUE TITLE
responseStatusInterceptor 执行顺序非预期

### ISSUE THREAD

**Issue by lemondreamtobe** [varletjs/axle#15]
axle请求 外层status 200
但是内层data为 {code: 401}
responseStatusInterceptor 只会执行validStatusHandler
invalidStatusHandler配置的401选项不会执行
表现上看起来就是 无论服务器返回什么（不局限于401 501 403），axle的状态始终是200，
导致始终会进validStatusHandler的逻辑

**Comment by haoziqaq** [comment]
很抱歉才看到您的 issue。
responseStatusInterceptor 是用于解析 http 状态码的，对于开发人员约定的业务状态码是没有作用的。
